version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  my_workflow:
    jobs:
      - build-and-test
      - build-and-publish-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - production
      - deploy-to-render:
          requires:
            - build-and-publish-docker-image

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.6

    steps:
      - checkout
      - run:
          name: Install
          command: poetry install --no-root
      - run:
          name: Run flake8
          command: poetry run flake8 .
      - run:
          name: Run tests
          command: poetry run pytest

  build-and-publish-docker-image:
    docker:
      - image: cimg/base:2023.06
    environment:
      DOCKER_IMAGE_NAME: lettings-auto-build
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and Push application Docker image
          command: |
              sudo chmod 666 /var/run/docker.sock
              echo "$DOCKERHUB_TOKEN" | docker login --username $DOCKERHUB_USERNAME --password-stdin
              docker build -t "$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME" .
              docker push "$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME"

  deploy-to-render:
    docker:
      - image: cimg/base:2023.06
    steps:
      - run:
          name: Deploy to Render
          command: |
              curl -X GET $RENDER_DEPLOY_HOOK_URL
