# Generated by Django 3.0 on 2024-01-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_copy_profiles_data'),
        ('oc_lettings_site', '0002_delete_letting_and_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
