# Generated by Django 3.0 on 2024-01-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20240102_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
